public enum KeynoteScripting: String {
    case application = "application"
    case audioclip = "audio clip"
    case cell = "cell"
    case character = "character"
    case chart = "chart"
    case column = "column"
    case document = "document"
    case group = "group"
    case iworkcontainer = "iWork container"
    case iworkitem = "iWork item"
    case image = "image"
    case line = "line"
    case masterslide = "master slide"
    case movie = "movie"
    case paragraph = "paragraph"
    case range = "range"
    case richtext = "rich text"
    case row = "row"
    case shape = "shape"
    case slide = "slide"
    case table = "table"
    case textitem = "text item"
    case theme = "theme"
    case word = "word"
}
